### ISSUE TITLE
文档表述错误

### ISSUE THREAD

**Issue by prokou** [decert-me/learnsolidity#23]
位置
docs/solidity-basic/12_receive.md

原文表述：而当我们要向合约里转入ETH时，情况比我们想象的复杂一些，被转入的合约需要明确表达其可以接收 ETH，以反正因合约没有处理的ETH的，导致ETH永远锁死在合约中。
”以防因合约没有处理的ETH的函数逻辑，导致ETH永远锁死在合约中“

原文表述：提示： ERC20 代币向合约转账时，并没有对合约经常类似的检查，因此也时不时会发生 ERC20 因误转入合约而锁死。
”并没有对合约经常类似的检查“这句话中的“经常”

原文表述：可以在合约中明确声明两个函数来表示合约时可以接收 ETH， 他们是 receive 函数和 fallback函数。
删去“时'

原文表述：当对合约进行转账时（不是使用MetaMask钱包转账，还是合约中使用addr.send()或者addr.transfer()对合约转账），合约在收到ETH时会执行receive函数。
”不论是使用MetaMask钱包转账“

**Comment by deanplus** [comment]
已修复：#24
